# Generated by Django 3.0.5 on 2020-05-11 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collegial_News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abstract', models.CharField(max_length=100, verbose_name='摘要')),
                ('date', models.DateField(verbose_name='发布时间')),
                ('link', models.CharField(max_length=100, verbose_name='网页链接')),
                ('content', models.TextField(verbose_name='新闻内容')),
                ('pic_link', models.TextField(verbose_name='图片链接')),
                ('category', models.CharField(max_length=200, verbose_name='所属类别')),
                ('viewtimes', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('collegial', models.CharField(max_length=30, verbose_name='所属学院')),
            ],
            options={
                'verbose_name': '学院新闻',
                'verbose_name_plural': '学院新闻',
                'db_table': '学院新闻表',
            },
        ),
        migrations.CreateModel(
            name='Inform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abstract', models.CharField(max_length=100, verbose_name='标题')),
                ('date', models.DateField(verbose_name='发布时间')),
                ('link', models.CharField(max_length=100, verbose_name='网页链接')),
                ('content', models.TextField(verbose_name='通告内容')),
                ('category', models.CharField(max_length=200, verbose_name='所属类别')),
                ('viewtimes', models.IntegerField(default=0, verbose_name='浏览次数')),
            ],
            options={
                'verbose_name': '通知公告',
                'verbose_name_plural': '通知公告',
                'db_table': '通知公告表',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abstract', models.CharField(max_length=100, verbose_name='摘要')),
                ('date', models.DateField(verbose_name='发布时间')),
                ('link', models.CharField(max_length=100, verbose_name='网页链接')),
                ('content', models.TextField(verbose_name='新闻内容')),
                ('pic_link', models.TextField(verbose_name='图片链接')),
                ('category', models.CharField(max_length=200, verbose_name='所属类别')),
                ('viewtimes', models.IntegerField(default=0, verbose_name='浏览次数')),
            ],
            options={
                'verbose_name': '学校新闻',
                'verbose_name_plural': '学校新闻',
                'db_table': '学校新闻表',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='登录名')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('grade', models.CharField(max_length=10, verbose_name='年级')),
                ('collegail', models.CharField(max_length=30, verbose_name='学院')),
                ('sex', models.CharField(max_length=2, verbose_name='性别')),
                ('major', models.CharField(max_length=30, verbose_name='专业')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': '用户信息表',
            },
        ),
        migrations.CreateModel(
            name='Browse_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infoID', models.CharField(max_length=20, verbose_name='信息ID')),
                ('infoCategory', models.CharField(max_length=20, verbose_name='信息类别')),
                ('viewtime', models.DateTimeField(verbose_name='浏览时间')),
                ('viewduration', models.IntegerField(verbose_name='浏览时长')),
                ('viewtimes', models.IntegerField(verbose_name='浏览次数')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apps.User')),
            ],
            options={
                'verbose_name': '浏览信息',
                'verbose_name_plural': '浏览信息',
                'db_table': '浏览信息表',
            },
        ),
    ]
